### ISSUE TITLE
你好我在运行train.py时提示 ModuleNotFoundError: No module named 'MIoUData' 使用conda或pip均无法解决，请问该如何处理这个问题？

### ISSUE THREAD

**Issue by WMZF** [cug103/NIGAN#2]
Traceback (most recent call last):
  File "E:/pytorch_project/NIGAN-main/train.py", line 14, in <module>
    from framework import MyFrame
  File "E:\pytorch_project\NIGAN-main\framework.py", line 4, in <module>
    import computeIOU
  File "E:\pytorch_project\NIGAN-main\computeIOU.py", line 2, in <module>
    from MIoUData import MIoU_dataloader
**ModuleNotFoundError: No module named 'MIoUData'**

**Comment by lovewjy** [comment]
请问你解决了嘛？
